theme: jekyll-theme-minimal

title: Shuyi Yang
description: I love building AI solutions to solve real world problems!

urls:
    linkedin: https://www.linkedin.com/in/shuyiyang/
    medium: https://medium.com/@ngshya
    github: https://github.com/ngshya

contacts:
    isp: shuyi.yang@intesasanpaolo.com

motto: What the caterpillar calls the end, the rest of the world calls a butterfly. - Lao Tze
